[package]
name = "bridge-hub-rococo-integration-tests"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "Bridge Hub Rococo runtime integration tests with xcm-emulator"
publish = false

[dependencies]
codec = { package = "parity-scale-codec", version = "3.4.0", default-features = false }

# Substrate
frame-support = { path = "../../../../../../substrate/frame/support", default-features = false}

# Polkadot
polkadot-core-primitives = { path = "../../../../../../infrablockspace/core-primitives", default-features = false}
polkadot-parachain-primitives = { path = "../../../../../../infrablockspace/parachain", default-features = false}
polkadot-runtime-parachains = { path = "../../../../../../infrablockspace/runtime/parachains" }
xcm = { package = "staging-xcm", path = "../../../../../../infrablockspace/xcm", default-features = false}
pallet-xcm = { path = "../../../../../../infrablockspace/xcm/pallet-xcm", default-features = false}

# Cumulus
parachains-common = { path = "../../../../common" }
cumulus-pallet-xcmp-queue = { path = "../../../../../pallets/xcmp-queue", default-features = false}
cumulus-pallet-dmp-queue = { path = "../../../../../pallets/dmp-queue", default-features = false}
pallet-bridge-messages = { path = "../../../../../../bridges/modules/messages", default-features = false}
bp-messages = { path = "../../../../../../bridges/primitives/messages", default-features = false}

# Local
xcm-emulator = { path = "../../../../../xcm/xcm-emulator", default-features = false}
integration-tests-common = { path = "../../common", default-features = false}
