[package]
name = "node-primitives"
description = "Primitives types for the Node-side"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bounded-vec = "0.7"
futures = "0.3.21"
primitives = { path = "../../primitives" }
parity-scale-codec = { version = "3.6.1", default-features = false, features = ["derive"] }
sp-core = { path = "../../../substrate/primitives/core" }
sp-application-crypto = { path = "../../../substrate/primitives/application-crypto" }
sp-consensus-babe = { path = "../../../substrate/primitives/consensus/babe" }
sp-keystore = { path = "../../../substrate/primitives/keystore" }
sp-maybe-compressed-blob = { path = "../../../substrate/primitives/maybe-compressed-blob" }
sp-runtime = { path = "../../../substrate/primitives/runtime" }
parachain-primitives = { path = "../../parachain", default-features = false }
schnorrkel = "0.9.1"
thiserror = "1.0.48"
serde = { version = "1.0.188", features = ["derive"] }

[target.'cfg(not(target_os = "unknown"))'.dependencies]
zstd = { version = "0.13.0", default-features = false }

[dev-dependencies]
erasure-coding = { package = "infrablockspace-erasure-coding", path = "../../erasure-coding" }
