[package]
name = "did-core-rpc"
version = "0.1.0"
edition = "2021"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
jsonrpsee = { version = "0.15.1", features = ["server", "macros"] }
thiserror = "1.0"
codec = { package = "parity-scale-codec", version = "3.0.0" }
serde = { version = "1.0.119", features = ["derive"] }

sp-rpc = { path = "../../primitives/rpc", default-features = false}
sp-runtime = { path = "../../primitives/runtime", default-features = false}
sp-api = { path = "../../primitives/api", default-features = false}
sp-blockchain = { path = "../../primitives/blockchain", default-features = false}

did-core = { version = "0.5.0", path = ".." }
