[relaychain]
default_command = "./target/release/infrablockspace"
default_args = ["-lparachain=debug", "-l=xcm=trace"]
chain = "infra-relay-local"

[[relaychain.nodes]]
name = "alice"
validator = true
args = ["-lparachain=debug", "-l=xcm=trace"]
rpc_port = 7100
ws_port = 7101

[[relaychain.nodes]]
name = "bob"
validator = true
args = ["-lparachain=debug", "-l=xcm=trace"]
rpc_port = 7200
ws_port = 7201

[[relaychain.nodes]]
name = "charlie"
validator = true
args = ["-lparachain=debug", "-l=xcm=trace"]
rpc_port = 7300
ws_port = 7301

[[relaychain.nodes]]
name = "dave"
validator = true
args = ["-lparachain=debug", "-l=xcm=trace"]
rpc_port = 7400
ws_port = 7401

[[relaychain.nodes]]
name = "ferdie"
validator = true
args = ["-lparachain=debug", "-l=xcm=trace"]
rpc_port = 7500
ws_port = 7501

# [[parachains]]
# id = 1000
# chain = "asset-hub-infra-local"
# cumulus_based = true

# # run alice as parachain collator
# [[parachains.collators]]
# name = "asset-hub-alice"
# validator = true
# args = ["-lparachain=debug", "-l=xcm=trace"]
# command = "./target/release/infra-parachain"
# rpc_port = 9500
# ws_port = 9501

# # run alice as parachain collator
# [[parachains.collators]]
# name = "asset-hub-bob"
# validator = true
# args = ["-lparachain=debug", "-l=xcm=trace"]
# command = "./target/release/infra-parachain"
# rpc_port = 9600
# ws_port = 9601

# [[parachains]]
# id = 1001
# chain = "contracts-infra-local"
# cumulus_based = true

# # run alice as parachain collator
# [[parachains.collators]]
# name = "contracts-infra-alice"
# validator = true
# args = ["-lparachain=debug", "-l=xcm=trace"]
# command = "./target/release/infra-parachain"
# rpc_port = 9700
# ws_port = 9701

# # run alice as parachain collator
# [[parachains.collators]]
# name = "contracts-infra-bob"
# validator = true
# args = ["-lparachain=debug", "-l=xcm=trace"]
# command = "./target/release/infra-parachain"
# rpc_port = 9800
# ws_port = 9801

[[parachains]]
id = 1002
chain = "did-infra-local"
cumulus_based = true

# run alice as parachain collator
[[parachains.collators]]
name = "did-infra-alice"
validator = true
args = ["-lparachain=debug", "-l=xcm=trace"]
command = "./target/release/infra-parachain"
rpc_port = 9900
ws_port = 9901

# run alice as parachain collator
[[parachains.collators]]
name = "did-infra-bob"
validator = true
args = ["-lparachain=debug", "-l=xcm=trace"]
command = "./target/release/infra-parachain"
rpc_port = 10000
ws_port = 10001

# [[parachains]]
# id = 2000
# chain = "urauth-local"
# cumulus_based = true

# # run alice as parachain collator
# [[parachains.collators]]
# name = "urauth-alice"
# validator = true
# args = ["-lparachain=debug", "-l=xcm=trace"]
# command = "./target/release/infra-parachain"
# rpc_port = 11000
# ws_port = 11001

# # run alice as parachain collator
# [[parachains.collators]]
# name = "urauth-bob"
# validator = true
# args = ["-lparachain=debug", "-l=xcm=trace"]
# command = "./target/release/infra-parachain"
# rpc_port = 12000
# ws_port = 12001
