[package]
name = "collator-protocol"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bitvec = { version = "1.0.1", default-features = false, features = ["alloc"] }
futures = "0.3.21"
futures-timer = "3"
gum = { package = "tracing-gum", path = "../../gum" }

sp-core = { path = "../../../../substrate/primitives/core" }
sp-runtime = { path = "../../../../substrate/primitives/runtime" }
sp-keystore = { path = "../../../../substrate/primitives/keystore" }

primitives = { path = "../../../primitives" }
node-network-protocol = { path = "../protocol" }
node-primitives = { path = "../../primitives" }
node-subsystem-util = { path = "../../subsystem-util" }
node-subsystem = { path = "../../subsystem" }
fatality = "0.0.6"
thiserror = "1.0.48"
tokio-util = "0.7.1"

[dev-dependencies]
log = "0.4.17"
env_logger = "0.9.0"
assert_matches = "1.4.0"

sp-core = { path = "../../../../substrate/primitives/core", features = ["std"] }
sp-keyring = { path = "../../../../substrate/primitives/keyring" }
sc-keystore = { path = "../../../../substrate/client/keystore" }
sc-network = { path = "../../../../substrate/client/network" }
parity-scale-codec = { version = "3.6.1", features = ["std"] }

node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
polkadot-primitives-test-helpers = { path = "../../../primitives/test-helpers" }
