[package]
name = "node-core-av-store"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
futures = "0.3.21"
futures-timer = "3.0.2"
kvdb = "0.13.0"
thiserror = "1.0.48"
gum = { package = "tracing-gum", path = "../../gum" }
bitvec = "1.0.0"

parity-scale-codec = { version = "3.6.1", features = ["derive"] }
erasure_coding = { package = "infrablockchain-erasure-coding", path = "../../../erasure-coding" }
node-subsystem = { path = "../../subsystem" }
node-subsystem-util = { path = "../../subsystem-util" }
infrablockchain-overseer = { path = "../../overseer" }
primitives = { path = "../../../primitives" }
node-primitives = { path = "../../primitives" }
sp-consensus = { path = "../../../../substrate/primitives/consensus/common", default-features = false }
node-jaeger = { path = "../../jaeger" }

[dev-dependencies]
log = "0.4.17"
env_logger = "0.9.0"
assert_matches = "1.4.0"
kvdb-memorydb = "0.13.0"

sp-core = { path = "../../../../substrate/primitives/core" }
node-subsystem-util = { path = "../../subsystem-util" }
node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
sp-keyring = { path = "../../../../substrate/primitives/keyring" }
parking_lot = "0.12.0"
test-helpers = { package = "polkadot-primitives-test-helpers", path = "../../../primitives/test-helpers" }
